api:
  dashboard: true

certificatesResolvers:
  default:
    acme:
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: my-email@my-domain.com
      storage: acme.json
      dnsChallenge:
        delayBeforeCheck: 0
        provider: digitalocean

entryPoints:
  web:
    address: ':80'
  web-secure:
    address: ':443'

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
